local here=debug.getinfo(1,'S').source:match('@?(.*/)') or './'
local seam=dofile(here..'definition_seam.lua')
local path=vim.fn.tempname()
local payload={request_id='one',term='term',definition='meaning'}
local function publish(doc)
  vim.fn.writefile({vim.json.encode(doc)},path..'.tmp')
  assert(vim.uv.fs_rename(path..'.tmp',path))
end
publish(payload)
local result,receipt=seam.read_result(path)
assert(vim.deep_equal(result,payload) and receipt,'reading definition must return its generation receipt')
publish({request_id='two',term='term',definition='new meaning'})
assert(not seam.clear_result(path,receipt),'old accepted result must not remove a replacement response')
assert(vim.fn.filereadable(path)==1)
result,receipt=seam.read_result(path)
assert(seam.clear_result(path,receipt),'accepted current generation may be consumed')
assert(vim.fn.filereadable(path)==0)
publish(payload)
result,receipt=seam.read_result(path)
publish(payload)
assert(not seam.clear_result(path,receipt),'byte-identical replacement is still a separate generation')
assert(not seam.clear_result(path),'deletion needs a receipt')
assert(vim.fn.filereadable(path)==1)
vim.fn.delete(path)
print('definition seam tests passed')
