package terminal

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	uv "github.com/charmbracelet/ultraviolet"
	"github.com/charmbracelet/x/ansi"
	"github.com/xianxu/pair/cmd/internal/ttyio"
)

type oracleCell struct {
	Text                             string
	Width                            int
	FG, BG                           int
	FGRGB, BGRGB                     bool
	Bold, Italic, Underline, Inverse bool
}
type oracleScreen struct {
	Lines       []string
	Cells       [][]oracleCell
	X, Y        int
	Links       []string
	Modes       map[string]any
	CursorStyle string
	CursorBlink bool
}

func runOracle(t *testing.T, cols, rows int, chunks []string) []oracleScreen {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Join(filepath.Dir(file), "../../../tests/terminal-oracle")
	if _, err := os.Stat(filepath.Join(dir, "node_modules/@xterm/headless/package.json")); err != nil {
		if os.Getenv("PAIR_TERMINAL_ORACLE") == "1" {
			t.Fatal("required oracle missing: run npm ci in tests/terminal-oracle")
		}
		t.Skip("independent oracle requires tests/terminal-oracle/run.sh (npm ci)")
	}
	input, err := json.Marshal(struct {
		Cols, Rows int
		Chunks     []string
	}{cols, rows, chunks})
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "node", "driver.cjs")
	cmd.Dir = dir
	cmd.Stdin = bytes.NewReader(input)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("oracle: %v\n%s", err, output)
	}
	var result []oracleScreen
	if err := json.Unmarshal(output, &result); err != nil {
		t.Fatalf("decode: %v: %s", err, output)
	}
	return result
}

func TestRendererIndependentWireOracle(t *testing.T) {
	child := testFrame(6, 2)
	child.Cells[0] = Cell{Content: "A", Width: 1, Style: uv.Style{Fg: ansi.IndexedColor(196), Attrs: uv.AttrBold}}
	child.Cells[1] = Cell{Content: "界", Width: 2}
	child.Cells[2] = Cell{}
	child.Cells[6] = Cell{Content: "Z", Width: 1, Style: uv.Style{Bg: ansi.RGBColor{R: 0x10, G: 0x20, B: 0x30}, Attrs: uv.AttrItalic | uv.AttrReverse, Underline: uv.UnderlineSingle}}
	child.Cursor = Cursor{X: 3, Y: 1, Visible: true, Shape: 3}
	bottom, err := StyledRows("\x1b]8;id=tab;https://example.com/a;b\x1b\\tabs\x1b]8;;\x1b\\", 6, 1)
	if err != nil {
		t.Fatal(err)
	}
	a, err := Compose(child, Geometry{Cols: 6, Rows: 3}, bottom)
	if err != nil {
		t.Fatal(err)
	}
	first, err := Render(Frame{}, a)
	if err != nil {
		t.Fatal(err)
	}
	b := a.Clone()
	b.EndpointID = "b"
	b.Cells[1] = Cell{Content: "x", Width: 1}
	b.Cells[2] = Cell{Content: "y", Width: 1}
	b.Cells[0].Style = uv.Style{}
	b.Cursor.X = 5
	b.Cursor.Y = 2
	second, err := Render(a, b)
	if err != nil {
		t.Fatal(err)
	}
	third, err := Render(b, a)
	if err != nil {
		t.Fatal(err)
	}
	// Leave the oracle with origin, margins and rendition that a compositor must
	// replace. Expectations below are literal, never generated by the Go backend.
	screens := runOracle(t, 6, 3, []string{"\x1b[2;3r\x1b[?6h\x1b[44m", string(first), string(second), string(third)})
	if len(screens) != 4 {
		t.Fatalf("snapshots %d", len(screens))
	}
	for _, i := range []int{1, 3} {
		s := screens[i]
		want := []string{"A界   ", "Z     ", "tabs  "}
		for y := range want {
			if s.Lines[y] != want[y] {
				t.Fatalf("snapshot %d row %d = %q want %q", i, y, s.Lines[y], want[y])
			}
		}
		if s.X != 3 || s.Y != 1 {
			t.Fatalf("cursor %d,%d", s.X, s.Y)
		}
		if !s.Cells[0][0].Bold || s.Cells[0][0].FG != 196 || s.Cells[0][1].Width != 2 || s.Cells[0][2].Width != 0 {
			t.Fatalf("wide/style %+v", s.Cells[0])
		}
		z := s.Cells[1][0]
		if z.BG != 0x102030 || !z.BGRGB || !z.Italic || !z.Inverse || !z.Underline {
			t.Fatalf("Z style %+v", z)
		}
	}
	if screens[2].Lines[0] != "Axy   " || screens[2].Cells[0][0].Bold || screens[2].X != 5 || screens[2].Y != 2 {
		t.Fatalf("diff %+v", screens[2])
	}
	found := false
	for _, link := range screens[1].Links {
		if link == "id=tab;https://example.com/a;b" {
			found = true
		}
	}
	if !found {
		t.Fatal("hyperlink params/URL lost")
	}
}

func TestRendererIndependentWideBoundaryDiff(t *testing.T) {
	a := testFrame(4, 2)
	a.Cells[2] = Cell{Content: "界", Width: 2}
	a.Cells[3] = Cell{}
	a.Cells[6] = Cell{Content: "界", Width: 2}
	a.Cells[7] = Cell{}
	b := a.Clone()
	b.Cells[2] = Cell{Content: "x", Width: 1}
	b.Cells[3] = Cell{Content: "y", Width: 1}
	b.Cells[5] = Cell{Content: "界", Width: 2}
	b.Cells[6] = Cell{}
	b.Cells[7] = Cell{Content: "z", Width: 1}
	c := testFrame(4, 2)
	c.Cells[7] = Cell{Content: "Q", Width: 1}
	first, err := Render(Frame{}, a)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Render(a, b)
	if err != nil {
		t.Fatal(err)
	}
	third, err := Render(b, c)
	if err != nil {
		t.Fatal(err)
	}
	screens := runOracle(t, 4, 2, []string{string(first), string(second), string(third)})
	want := [][]string{{"  界", "  界"}, {"  xy", " 界z"}, {"    ", "   Q"}}
	for i := range want {
		for y := range want[i] {
			if screens[i].Lines[y] != want[i][y] {
				t.Fatalf("snapshot %d row %d: %q, want %q", i, y, screens[i].Lines[y], want[i][y])
			}
		}
	}
}

// Every accepted prefix is a possible physical terminal state when writing
// fails. Exercise production Select and Release, then ordinary shell text;
// the independent interpreter must see the documented released state.
func TestRendererIndependentInterruptedPresentationRelease(t *testing.T) {
	paint := func(prefix int) string {
		t.Helper()
		parent := ttyio.NewFake()
		e, err := NewEndpoint("release", Geometry{8, 4}, ttyio.NewFake())
		if err != nil {
			t.Fatal(err)
		}
		defer e.Close()
		if _, err := e.Feed([]byte("\x1b[31;44;1;3;4m\x1b]8;id=test;https://example.com\x1b\\LINK\x1b[6 q\x1b[?25l"), time.Now()); err != nil {
			t.Fatal(err)
		}
		p := NewPresenter(parent, AnyMotion)
		boom := errors.New("interrupted presentation")
		if prefix >= 0 {
			parent.Enqueue(ttyio.WriteStep{Limit: prefix, ZeroProgress: prefix == 0, Err: boom})
		}
		err = p.Select(context.Background(), e, Geometry{8, 5}, make([]Cell, 8))
		if prefix < 0 && err != nil || prefix >= 0 && !errors.Is(err, boom) {
			t.Fatalf("prefix %d: select %v", prefix, err)
		}
		if err := p.Release(context.Background()); err != nil {
			t.Fatalf("prefix %d: release %v", prefix, err)
		}
		return string(parent.Bytes())
	}
	// The successful wire contains both painting and cleanup. Testing extra
	// offsets beyond paint length also covers a fully accepted failing write.
	complete := paint(-1)
	chunks := make([]string, 0, len(complete)+1)
	for prefix := 0; prefix <= len(complete); prefix++ {
		chunks = append(chunks, "\x1bc\x1b[2;4r\x1b[?6h"+paint(prefix)+"\x1b[H\x1b[2JABCDEFGHI")
	}
	for prefix, screen := range runOracle(t, 8, 5, chunks) {
		if screen.Lines[0] != "ABCDEFGH" || screen.Lines[1] != "I       " || screen.X != 1 || screen.Y != 1 {
			t.Errorf("prefix %d: released text/cursor rows=%q cursor=%d,%d", prefix, screen.Lines[:2], screen.X, screen.Y)
			break
		}
		for _, mode := range []string{"originMode", "bracketedPasteMode", "sendFocusMode"} {
			if screen.Modes[mode] != false {
				t.Errorf("prefix %d: %s=%v", prefix, mode, screen.Modes[mode])
			}
		}
		if screen.Modes["wraparoundMode"] != true || screen.Modes["mouseTrackingMode"] != "none" {
			t.Errorf("prefix %d: modes=%v", prefix, screen.Modes)
		}
		if screen.CursorStyle != "block" || !screen.CursorBlink {
			t.Errorf("prefix %d: cursor style=%s blink=%v", prefix, screen.CursorStyle, screen.CursorBlink)
		}
		cell := screen.Cells[0][0]
		if cell.Bold || cell.Italic || cell.Underline || cell.Inverse || cell.FG != -1 || cell.BG != -1 {
			t.Errorf("prefix %d: leaked rendition %+v", prefix, cell)
		}
		if len(screen.Links) > 0 && screen.Links[len(screen.Links)-1] != ";" {
			t.Errorf("prefix %d: open hyperlink=%q", prefix, screen.Links[len(screen.Links)-1])
		}
	}
}

func TestRendererIndependentCombiningClusters(t *testing.T) {
	endpoint, err := NewEndpoint("combining", Geometry{8, 2}, ttyio.NewFake())
	if err != nil {
		t.Fatal(err)
	}
	defer endpoint.Close()
	if _, err := endpoint.Feed([]byte("e\u0301界"), time.Now()); err != nil {
		t.Fatal(err)
	}
	frame, err := endpoint.Snapshot(time.Now())
	if err != nil {
		t.Fatal(err)
	}
	chrome, err := StyledRows("e\u0301", 8, 1)
	if err != nil {
		t.Fatal(err)
	}
	composed, err := Compose(frame, Geometry{8, 3}, chrome)
	if err != nil {
		t.Fatal(err)
	}
	wire, err := Render(Frame{}, composed)
	if err != nil {
		t.Fatal(err)
	}
	screen := runOracle(t, 8, 3, []string{string(wire)})[0]
	if screen.Cells[0][0].Text != "e\u0301" || screen.Cells[0][0].Width != 1 || screen.Cells[0][1].Text != "界" || screen.Cells[0][1].Width != 2 || screen.Cells[2][0].Text != "e\u0301" {
		t.Fatalf("combining cells=%+v chrome=%+v", screen.Cells[0], screen.Cells[2])
	}
}
